version: '2.1'

services:
  app:
    image: ambientum/php:7.1-nginx
    container_name: teste_simsave
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    links:
      - mysql
    environment:
      - XDEBUG_ENABLED=true
      - PHP_IDE_CONFIG=serverName=ambientum

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=teste_simsave
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"

  mysql-testing:
    image: mysql:5.7
    container_name: mysql-testing
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=teste_simsave_testing
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3307:3306"
